# these are the steps for make file for producing the full rag and cv pipeline

# 1. first install all dependencies
install:
	pip install -r requirements.txt

# 2. Run the Full Pipeline
rag:
	python backend/pipeline.py

# 3. Run just the API
run-app:
	cd backend && uvicorn app:app --reload

# 4. Clean up logs and cache
clean:
	rm -rf __pycache__
	rm -rf backend/__pycache__
	rm -rf backend/models/flora_cv_onnx
	rm -rf backend/models/flora_rag_db
